[ADVAPP-941]: Update knowledge management to serve as the resource hub for a customer
canyongbs/advisingapp pull request #1096
Opened 2024-11-04 08:24 UTC by payal-canyon

### Ticket(s) or GitHub Issue

- https://canyongbs.atlassian.net/browse/ADVAPP-941

### Technical Description

> Update knowledge management to serve as the resource hub for a customer

### Any deployment steps required?

> No

### Are any Feature Flags and/or Data Migrations that can eventually be removed Added?

> Yes. `ResourceHub`

_______________________________________________

#### Before contributing and submitting this PR, make sure you have Read, agree, and are compliant with the [contributing guidelines](https://github.com/canyongbs/advisingapp/blob/main/README.md#contributing).

2024-11-05 07:43 UTC, payal-canyon commented
Hi @Orrison 

The classes' renaming from knowledge base/management to resource hub has been done, and as per the discussion, I created the PR for review. Meanwhile, I started working on the next part, which is the renaming of tables and columns.

Thank You!

2024-11-18 23:03 UTC, Orrison requested changes

2024-11-18 23:03 UTC, Orrison commented on app-modules/resource-hub/database/migrations/2024_11_05_121450_data_migrate_knowledge_base_related_data_to_resource_hub.php
Similiar to the other comments, you cannot drop the views until after the Feature Flag is toggled. As doing so will result in downtime

2024-11-18 23:03 UTC, Orrison commented on app-modules/resource-hub/database/migrations/2024_10_30_055640_data_migration_knowledge_base_to_resource_hub_permissions.php
This will need to be wrapped in a transaction with a Feature Flag being toggled in the end. Or we will end up with a state in the application where checked permissions will fail.

2024-11-21 19:35 UTC, merged