[ADVAPP-987]: Feature Flag Cleanup: ProspectStatusSystemProtectionAndAutoAssignment
canyongbs/advisingapp pull request #1105
Opened 2024-11-08 12:48 UTC by ankit-canyon

### Ticket(s) or GitHub Issue

- https://canyongbs.atlassian.net/browse/ADVAPP-987

### Technical Description

> Feature flag clean-up for "ProspectStatusSystemProtectionAndAutoAssignment".

### Any deployment steps required?

>  No.

### Are any Feature Flags and/or Data Migrations that can eventually be removed Added?

> No.
_______________________________________________

#### Before contributing and submitting this PR, make sure you have Read, agree, and are compliant with the [contributing guidelines](https://github.com/canyongbs/advisingapp/blob/main/README.md#contributing).

2024-11-08 17:48 UTC, Orrison submitted a review, later dismissed

2024-11-12 13:38 UTC, danharrin requested changes

2024-11-12 13:38 UTC, danharrin commented on .config/psysh/psysh_history
Can you remove this file please?

2024-11-13 11:48 UTC, danharrin approved these changes

2024-11-13 12:00 UTC, merged