[ADVAPP-966]: Introduce the ability for alert statuses to be configurable by institutions
canyongbs/advisingapp pull request #1123
Opened 2024-11-20 09:59 UTC by jayushi-canyon

### Ticket(s) or GitHub Issue

- https://canyongbs.atlassian.net/browse/ADVAPP-966

### Technical Description

> Create alert status table and make its relationship with alert table.

### Any deployment steps required?

> No.

### Are any Feature Flags and/or Data Migrations that can eventually be removed Added?

> FeatureFlag: AlertStatusId
> Data Migration: 2024_11_19_112341_data_change_status_to_status_id_in_histories_table.php
2024_11_17_093824_data_add_data_in_status_id_in_alerts_table.php
> Need to create one data migration which removes status column from alert table.

_______________________________________________

#### Before contributing and submitting this PR, make sure you have Read, agree, and are compliant with the [contributing guidelines](https://github.com/canyongbs/advisingapp/blob/main/README.md#contributing).

2024-11-20 19:12 UTC, Orrison requested changes
This currently has test errors, lint errors, and a merge conflict.

2024-11-22 15:24 UTC, Orrison requested changes
Some notes.

Overall as well I think you can adjust any of the History changes you made to not add `status_id` but just changed what is saved into `status` as the name of the AlertStatus record.
Currently histories just save static at the time data. So just changing where it gets that should work just fine.

2024-11-22 15:24 UTC, Orrison commented on app-modules/campaign/src/Filament/Blocks/ProactiveAlertBlock.php
> +                ->default(SystemAlertStatusClassification::default())
This will need to be a query to get the default from the database

2024-11-22 15:24 UTC, Orrison commented on app-modules/campaign/src/Filament/Blocks/ProactiveAlertBlock.php
> +                ->visible(AlertStatusId::active() == false),
```suggestion
                ->visible(! AlertStatusId::active()),
```

2024-11-22 15:24 UTC, Orrison commented on app-modules/campaign/tests/Actions/ProactiveAlertsCampaignTest.php
> +    // expect(Alert::first()->status()->name)->toBe(SystemAlertStatusClassification::Active);
This should test that the status is what we would expect.

2024-11-22 15:24 UTC, Orrison commented on app-modules/campaign/src/Filament/Blocks/ProactiveAlertBlock.php
> +                ->default(SystemAlertStatusClassification::default())
This should probably be wrapped in a closure.

2024-11-22 15:24 UTC, Orrison commented on app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectAlerts.php
> +                    ->default(SystemAlertStatusClassification::default())
This won't work here because you changed the `default` to return the Model. So you will need to hard code the correct default enum.

2024-11-22 15:24 UTC, Orrison commented on app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectAlerts.php
> +                    ->visible(AlertStatusId::active() == false),
```suggestion
                    ->visible(! AlertStatusId::active()),
```

2024-11-22 15:24 UTC, Orrison commented on app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectAlerts.php
> +                    ->default(SystemAlertStatusClassification::default())
This should probably be wrapped in a closure.

2024-11-22 15:24 UTC, Orrison commented on app-modules/prospect/src/Filament/Widgets/ProspectStats.php
> +                    return $user->prospectAlerts()->status(SystemAlertStatusClassification::Active)->count();
Does this need to change based on the Feature flag to check the relationship rather than by ENUM now?

2024-11-22 15:24 UTC, Orrison commented on app-modules/report/src/Filament/Exports/StudentExporter.php
> +                SystemAlertStatusClassification::cases(),
This will need to change based on the Feature flag to get the values from the relationship instead.

2024-11-22 15:24 UTC, Orrison commented on app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/StudentAlertsRelationManager.php
> +                    ->default(SystemAlertStatusClassification::default())
This won't work because you changed `default` to return the Model not the ENUM

2024-11-22 15:24 UTC, Orrison commented on app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/StudentAlertsRelationManager.php
> +                    ->visible(AlertStatusId::active() == false),
```suggestion
                    ->visible(! AlertStatusId::active()),
```

2024-11-22 15:24 UTC, Orrison commented on app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/StudentAlertsRelationManager.php
> +                    ->default(SystemAlertStatusClassification::default())
This probably should be wrapped in a Closure

2024-11-22 15:24 UTC, Orrison commented on app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/StudentAlertsRelationManager.php
> +                    ->visible(AlertStatusId::active() == false),
```suggestion
                    ->visible(! AlertStatusId::active()),
```

2024-11-22 15:24 UTC, Orrison commented on app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/StudentAlertsRelationManager.php
> +                    ->visible(AlertStatusId::active() == false),
```suggestion
                    ->visible(! AlertStatusId::active()),
```

2024-11-22 15:24 UTC, Orrison commented on app-modules/student-data-model/src/Filament/Widgets/StudentStats.php
> +                    return $user->studentAlerts()->status(SystemAlertStatusClassification::Active)->count();
This should be updated to check the relationship or this old way based on the Feature Flag

2024-11-22 15:24 UTC, Orrison commented on database/migrations/2024_11_14_152015_add_feature_flag_alert_status_id.php
This should probably be renamed `activate` rather than `add` and contain the prefix `data_`

2024-11-22 15:24 UTC, Orrison commented on database/migrations/2024_11_17_062514_seed_permissions_for_alert_status.php
This migration should be moved to the Module. Also, make sure the feature flag activation is run after this and any other migration to prevent downtime or issues.

2024-11-22 15:24 UTC, Orrison commented on database/migrations/2024_11_17_093824_data_add_data_in_status_id_in_alerts_table.php
> +        });
This is roughly the idea but please refer to my previous comment on the migration order and responsibility.

2024-11-22 15:24 UTC, Orrison commented on database/migrations/2024_11_19_112341_data_change_status_to_status_id_in_histories_table.php
Let's actually remove this. After reviewing what the Histories are doing, it is just storing a text representation of the status at the time the History record is created. So there is no need for a data fix.

2024-11-22 15:24 UTC, Orrison commented on app-modules/alert/src/Filament/Actions/AlertHistoryCreatedViewAction.php
> +                        ->visible(AlertStatusId::active() == false),
```suggestion
                        ->visible(! AlertStatusId::active()),
```

2024-11-25 16:19 UTC, jayushi-canyon commented on app-modules/alert/database/migrations/2024_11_12_171318_create_alert_statuses_table.php
> +            $table->integer('sort')->default(0);
@Orrison I initially kept the name 'order' only but then i took reference from 'prospect_statuses' table where the column name is 'sort'.

2024-11-26 12:51 UTC, Orrison commented on app-modules/alert/database/migrations/2024_11_12_171318_create_alert_statuses_table.php
> +            $table->integer('sort')->default(0);
@jayushi-canyon yeah no problem. We have been using `order` in all new places. So we will go back and change that `sort` in `prospect_statuses` another time.

2024-11-26 18:10 UTC, jayushi-canyon commented on database/migrations/2024_11_19_112341_data_change_status_to_status_id_in_histories_table.php
@Orrison based on this change I have also made changes in app-modules/alert/src/Histories/AlertHistory.php,
so that user can see accurate data.

2024-11-27 16:04 UTC, Orrison requested changes
Please review all your changes and make sure that you are using the column name `order` now that you have changed it from `sort`.

2024-11-27 16:04 UTC, Orrison commented on app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectAlerts.php
> +                    ->relationship('status', 'name', fn (Builder $query) => $query->orderBy('sort'))
This column was supposed to be changed to `order`

2024-11-27 16:04 UTC, Orrison commented on app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/StudentAlertsRelationManager.php
> +                    ->relationship('status', 'name', fn (Builder $query) => $query->orderBy('sort'))
This column should be called `order`

2024-11-27 16:04 UTC, Orrison commented on app-modules/student-data-model/src/Filament/Widgets/StudentStats.php
> +                            $query->where('classification', SystemAlertStatusClassification::Active); // Replace `status_column` with your actual column name
Is this comment needed?

2024-11-27 16:04 UTC, Orrison commented on database/migrations/2024_11_19_112341_data_change_status_to_status_id_in_histories_table.php
> +                if (isset($alertData->status) && $alertData->status == $status->classification) {
```suggestion
                if (isset($alertData->status) && $alertData->status === $status->classification) {
```

2024-11-27 16:04 UTC, Orrison commented on app-modules/alert/src/Models/AlertStatus.php
> +        'is_default',
This can have `order` added to it

2024-11-27 19:36 UTC, closed without merging