[ADVAPP-995]: Improve the UI/UX design of the student profile page
canyongbs/advisingapp pull request #1128
Opened 2024-11-21 19:21 UTC by danharrin

### Ticket(s) or GitHub Issue

- https://canyongbs.atlassian.net/browse/ADVAPP-995

### Technical Description

Rebuilds the student profile page with an improved design.

### Any deployment steps required?

No

### Are any Feature Flags and/or Data Migrations that can eventually be removed Added?

No

_______________________________________________

#### Before contributing and submitting this PR, make sure you have Read, agree, and are compliant with the [contributing guidelines](https://github.com/canyongbs/advisingapp/blob/main/README.md#contributing).

2024-11-26 15:07 UTC, danharrin commented on app-modules/student-data-model/resources/views/filament/resources/student-resource/view-student.blade.php
> +                            'manageUrl' => \AdvisingApp\StudentDataModel\Filament\Resources\StudentResource::getUrl('alerts', ['record' => $this->getRecord()]),
Done

2024-11-26 15:08 UTC, danharrin commented on app-modules/student-data-model/src/Filament/Resources/EducatableResource/Widgets/EducatableActivityFeedWidget.php
> +    use CanLoadTimelineRecords; // @todo: Refactor
This refers to the timeline refactor ticket

2024-11-26 15:08 UTC, danharrin commented on app-modules/student-data-model/src/Filament/Resources/EducatableResource/Widgets/EducatableActivityFeedWidget.php
> +        // @todo: Refactor
As above

2024-11-26 15:08 UTC, danharrin commented on app-modules/student-data-model/src/Filament/Resources/EducatableResource/Widgets/EducatableActivityFeedWidget.php
> +    // @todo: Refactor
As above

2024-11-26 15:42 UTC, Orrison requested changes
Some strange UI issues on mobile:
<img width="798" alt="Screenshot 2024-11-26 at 10 40 04 AM" src="https://github.com/user-attachments/assets/bee77f1d-53d2-437e-aa6d-e531ff91dff4">

Also there is a console error when opening the timeline full view:
[test.advisingapp.local-1732635738177.log](https://github.com/user-attachments/files/17921988/test.advisingapp.local-1732635738177.log)

2024-11-26 17:18 UTC, danharrin commented
I have addressed both @Orrison

2024-11-27 13:40 UTC, Orrison approved these changes
Great work on this one @danharrin!

2024-11-27 13:51 UTC, merged