[ADVAPP-979]: Enhance the user list experience by introducing a filter for "no assigned team"
canyongbs/advisingapp pull request #1129
Opened 2024-11-22 09:41 UTC by amit-canyon

### Ticket(s) or GitHub Issue

- https://canyongbs.atlassian.net/browse/ADVAPP-979

### Technical Description

> Enhance the user list experience by introducing a filter for "no assigned team"

### Any deployment steps required?

>No

### Are any Feature Flags and/or Data Migrations that can eventually be removed Added?

> No

_______________________________________________

#### Before contributing and submitting this PR, make sure you have Read, agree, and are compliant with the [contributing guidelines](https://github.com/canyongbs/advisingapp/blob/main/README.md#contributing).

2024-11-25 15:03 UTC, amit-canyon commented on app-modules/authorization/tests/Feature/Filament/Resources/User/ListUsersTest.php
> +        );
@danharrin  & @Orrison 
Sure , i will this. Also i will make same change my another PR that related to the filter ass well. 
Thanks!.

2024-11-25 18:16 UTC, danharrin reviewed
The options are not grouped yet, did you try that bit of the ticket?

2024-11-26 04:09 UTC, amit-canyon commented
> The options are not grouped yet, did you try that bit of the ticket?

@danharrin  Sorry, but i didn't getting you, please explain little bit more here. Thanks.

2024-11-26 13:37 UTC, Orrison requested changes

2024-11-26 13:37 UTC, Orrison commented on app/Filament/Resources/UserResource/Pages/ListUsers.php
> +            ...$teams,
It is expected that this options are grouped: https://filamentphp.com/docs/3.x/forms/fields/select#grouping-options

2024-11-27 16:32 UTC, Orrison approved these changes

2024-11-27 16:44 UTC, merged