[ADVAPP-1042]: Refactor product administration permissions to include People Administration and purge legacy permissions
canyongbs/advisingapp pull request #1165
Opened 2024-12-06 23:58 UTC by danharrin

### Ticket(s) or GitHub Issue

- https://canyongbs.atlassian.net/browse/ADVAPP-1042

### Technical Description

Replaces permissions, deletes old ones. Deletes groups without any permissions. Removes unnessecary parent permission checks for settings pages (settings page parent class doesn't have permission checks in the first place).

### Any deployment steps required?

No

### Are any Feature Flags and/or Data Migrations that can eventually be removed Added?

No

_______________________________________________

#### Before contributing and submitting this PR, make sure you have Read, agree, and are compliant with the [contributing guidelines](https://github.com/canyongbs/advisingapp/blob/main/README.md#contributing).

2024-12-10 20:02 UTC, Orrison requested changes
Looks great! Just a nit to update all instances of ->id to ->getKey() while we are in these Policies.

2024-12-10 20:02 UTC, Orrison commented on app/Policies/NotificationSettingPolicy.php
Since we are in this file right now, would you mind changing all calls to `id` to `getKey()`?

2024-12-10 20:02 UTC, Orrison commented on app/Policies/PronounsPolicy.php
Since we are in this file right now, would you mind changing all calls to `id` to `getKey()`?

2024-12-11 13:29 UTC, danharrin commented
@Orrison I have replaced these instances across the entire codebase

2024-12-11 16:55 UTC, Orrison approved these changes

2024-12-11 17:06 UTC, merged