[ADVAPP-1050]: Enhance permissions with a matrix role editor
canyongbs/advisingapp pull request #1174
Opened 2024-12-10 14:04 UTC by danharrin

### Ticket(s) or GitHub Issue

- https://canyongbs.atlassian.net/browse/ADVAPP-1050

### Technical Description

Introduce new `PermissionMatrix` field to manage role permissions across Create, View and Edit pages.

### Any deployment steps required?

No

### Are any Feature Flags and/or Data Migrations that can eventually be removed Added?

No

_______________________________________________

#### Before contributing and submitting this PR, make sure you have Read, agree, and are compliant with the [contributing guidelines](https://github.com/canyongbs/advisingapp/blob/main/README.md#contributing).

2024-12-10 21:58 UTC, Orrison reviewed
This all looks and works great! Even on mobile, which is awesome.

I looked through the list of remaining permissions you sent me and will create a separate ticket to address most of them. But some of them are for `import` which we do have setup in some of our policies and I think we should keep.

Would it be easy to add `import` after `restore`?

Asked Product in the ticket if they want this or not.

2024-12-10 22:24 UTC, Orrison requested changes
Per discussion with Product in the ticket, let's add `import` into the matrix as well after `delete` and before `force-delete`

2024-12-11 13:11 UTC, danharrin commented
@Orrison added Import

2024-12-11 16:25 UTC, Orrison approved these changes

2024-12-11 16:36 UTC, merged