[ADVAPP-1068]: Adjust the opacity of the checkboxes on the role view page when using light mode
canyongbs/advisingapp pull request #1182
Opened 2024-12-13 11:44 UTC by amit-canyon

### Ticket(s) or GitHub Issue

- https://canyongbs.atlassian.net/browse/ADVAPP-1068

### Technical Description

> Adjust the opacity of the checkboxes on the role view page when using light mode

### Any deployment steps required?

> No

### Are any Feature Flags and/or Data Migrations that can eventually be removed Added?

> No

_______________________________________________

#### Before contributing and submitting this PR, make sure you have Read, agree, and are compliant with the [contributing guidelines](https://github.com/canyongbs/advisingapp/blob/main/README.md#contributing).

2024-12-13 17:53 UTC, Orrison reviewed
This looks correct but @danharrin may work with this to fix it in Filament as well so leaving it up to you @danharrin for approval on this ticket.

2024-12-17 13:07 UTC, danharrin requested changes
I have just made a Filament release that should solve the issue, can you please update Filament, build NPM, test that it works, and then remove this new line if it does?

Please let me know if it doesn't solve

2024-12-17 17:02 UTC, amit-canyon commented
> I have just made a Filament release that should solve the issue, can you please update Filament, build NPM, test that it works, and then remove this new line if it does?
> 
> Please let me know if it doesn't solve

@danharrin  I have tried to update filament but it say nothing to update.

2024-12-18 14:46 UTC, Orrison approved these changes

2024-12-18 15:04 UTC, merged