[ADVAPP-29]: Implement Twilio Settings
canyongbs/advisingapp pull request #389
Opened 2023-12-21 20:21 UTC by mxm1070

### Ticket(s) or GitHub Issue

https://canyongbs.atlassian.net/browse/ADVAPP-28

### Technical Description

Move Twilio related settings from the env into a settings page.

### Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [x] New feature (non-breaking change which adds functionality)

### Screenshots (if appropriate)

### Any deployment steps required?

A deployment step could be a command that needs to be executed or an ENV key that needs to be added, for example.

- [x] Yes, please specify

The following env keys have been removed:
```
TWILIO_ACCOUNT_SID
TWILIO_AUTH_TOKEN
```
`TWILIO_FROM_NUMBER` has been renamed to `TWILIO_TEST_FROM_NUMBER` to keep the existing Student seeder functionality.
_______________________________________________

## Before contributing and submitting this PR, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/canyongbs/advisingapp/blob/main/README.md#contributing).
* [x] Title the PR with the ticket/issue number and a short description of the changes made. Or if no ticket/issue exists, title the PR with a short description of the changes made
* [x] Linked a relevant ticket or issue or describe the issue/feature which this PR resolves/implements.
* [x] Resolved all conflicts, if any.
* [x] Rebased your branch PR on top of the latest upstream `develop` branch.

2023-12-21 21:27 UTC, Orrison submitted a review, later dismissed

2023-12-21 22:29 UTC, dgoetzit requested changes

2023-12-21 22:29 UTC, dgoetzit commented on app-modules/in-app-communication/src/Filament/Pages/UserChat.php
> +                accountSid: $settings->from_number,
This needs to be 
```suggestion
                accountSid: $settings->account_sid,
```

2023-12-21 22:29 UTC, dgoetzit commented on app-modules/integration-twilio/src/Providers/IntegrationTwilioServiceProvider.php
> +        Relation::morphMap([]);
This can be removed.

2023-12-22 00:38 UTC, dgoetzit approved these changes

2023-12-22 17:25 UTC, merged