Feature/advapp 135 implement slider survey question type
canyongbs/advisingapp pull request #423
Opened 2024-01-05 22:58 UTC by mxm1070

### Ticket(s) or GitHub Issue

https://canyongbs.atlassian.net/browse/ADVAPP-135

### Technical Description

Implemented slider survey question type. The functionality is there with some styling, but I can't figure out how to make it respect the primary color passed in from the survey resource for either the slider or the input border color.

### Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [x] New feature (non-breaking change which adds functionality)

### Screenshots (if appropriate)

### Any deployment steps required?

A deployment step could be a command that needs to be executed or an ENV key that needs to be added, for example.

- [x] No

_______________________________________________

## Before contributing and submitting this PR, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/canyongbs/advisingapp/blob/main/README.md#contributing).
* [x] Title the PR with the ticket/issue number and a short description of the changes made. Or if no ticket/issue exists, title the PR with a short description of the changes made
* [x] Linked a relevant ticket or issue or describe the issue/feature which this PR resolves/implements.
* [x] Resolved all conflicts, if any.
* [x] Rebased your branch PR on top of the latest upstream `develop` branch.

2024-01-08 15:08 UTC, Orrison requested changes
This looks great. No notes on any of the code so far. But let's take care of the following:

- Check with Product as to whether or not the field should indeed be statically 1-5, or if the User should be able to specify a min/max and then ensure the implementation of the decision.
- Sync with @danharrin to see how he got buttons and everything else to adhere to the form color that was chosen, and then implement.

2024-01-08 15:08 UTC, Orrison commented on app-modules/survey/src/Filament/Blocks/SliderSurveyFieldBlock.php
> +        ];
Regardless of whether or not min/max remains static or becomes user-configurable, let's make sure that min/max is enforced here.

2024-01-08 19:49 UTC, mxm1070 commented
Product said configuration will come in the future.

2024-01-09 13:58 UTC, Orrison approved these changes

2024-01-09 13:58 UTC, merged