[ADVAPP-219]: Process for creating a new tenant
canyongbs/advisingapp pull request #467
Opened 2024-01-24 03:10 UTC by Orrison

### Ticket(s) or GitHub Issue

- https://canyongbs.atlassian.net/browse/ADVAPP-219

### Technical Description

Adds a protected API endpoint to create a tenant. Attached is a postman export for a request. 

[Landlord API.postman_collection.json](https://github.com/canyongbs/advisingapp/files/14032124/Landlord.API.postman_collection.json)

### Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Content or styling update (Changes which don't affect functionality)
- [ ] DevOps
- [ ] Documentation

### Screenshots (if appropriate)

### Any deployment steps required?

A deployment step could be a command that needs to be executed or an ENV key that needs to be added, for example.

- [x] Yes, please specify
- [ ] No

Will need to add the LANDLORD_API_KEY env variable to demo.

_______________________________________________

## Before contributing and submitting this PR, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/canyongbs/advisingapp/blob/main/README.md#contributing).
* [x] Title the PR with the ticket/issue number and a short description of the changes made. Or if no ticket/issue exists, title the PR with a short description of the changes made
* [x] Linked a relevant ticket or issue or describe the issue/feature which this PR resolves/implements.
* [x] Resolved all conflicts, if any.
* [x] Rebased your branch PR on top of the latest upstream `develop` branch.

2024-01-24 22:00 UTC, mxm1070 requested changes
Also I just noticed the copyright is still 2023, should that be updated?

2024-01-25 18:53 UTC, Orrison commented on app/Console/Commands/GenerateLandlordApiKey.php
> +            return false;
It is, but I would prefer making this command better at a later time. I simply copied the code from the Laravel key generate to make use for what we need right now.

2024-01-25 19:08 UTC, Orrison commented
> Also I just noticed the copyright is still 2023, should that be updated?

I am unsure, I will check. But changing that would be beyond the scope of this item.

2024-01-25 19:24 UTC, mxm1070 approved these changes

2024-01-25 19:29 UTC, merged