[ADVAPP-291]: Performance improvements
canyongbs/advisingapp pull request #500
Opened 2024-02-05 17:52 UTC by danharrin

### Ticket(s) or GitHub Issue

- https://canyongbs.atlassian.net/browse/ADVAPP-291

### Technical Description

Todo:

- [ ] Add `icons:cache` to local dev env as well as deployment scripts for staging/prod
- [ ] Update Filament for https://github.com/filamentphp/filament/pull/11258
- [ ] Add `filament:cache-components` to deployment scripts for staging/prod
- [ ] Add `optimize` to deployment scripts for staging/prod if not present already

### Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Content or styling update (Changes which don't affect functionality)
- [x] DevOps
- [ ] Documentation

### Screenshots (if appropriate)

### Any deployment steps required?

A deployment step could be a command that needs to be executed or an ENV key that needs to be added, for example.

- [x] Yes, please specify
- [ ] No

_______________________________________________

## Before contributing and submitting this PR, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/canyongbs/advisingapp/blob/main/README.md#contributing).
* [x] Title the PR with the ticket/issue number and a short description of the changes made. Or if no ticket/issue exists, title the PR with a short description of the changes made
* [x] Linked a relevant ticket or issue or describe the issue/feature which this PR resolves/implements.
* [x] Resolved all conflicts, if any.
* [x] Rebased your branch PR on top of the latest upstream `main` branch.

2024-02-05 17:52 UTC, danharrin commented
Hey @Orrison there are some commands in the todo section that could be added to the Docker setups, just making you aware these are here.

2024-02-08 13:51 UTC, Orrison requested changes
Sorry one small improvement that I found out later on

2024-02-08 13:51 UTC, Orrison commented on docker/s6-overlay/scripts/cache-icons
> +  echo "Icons cached!"
```suggestion
  echo "Caching icons..."
  
  USERNAME=$(id -nu $PUID)

  s6-setuidgid $USERNAME php $WEBUSER_HOME/artisan icons:cache

  echo "Icons cached!"
```

2024-02-08 20:23 UTC, Orrison approved these changes

2024-02-08 20:23 UTC, merged