[ADVAPP-412]: Spike: Enhanced Branding Package (Themes)
canyongbs/advisingapp pull request #605
Opened 2024-03-18 17:06 UTC by danharrin

### Ticket(s) or GitHub Issue

- https://canyongbs.atlassian.net/browse/ADVAPP-412

### Technical Description

Test configuration is being temporarily stored in `custom-example.css`.

The CSS is stored in the database and published to `custom.css` when updated. This gets built alongside the main Tailwind build so it can use compilation features such as `@apply`.

Connection to Olympus is initiated by making a request to a signed URL to issue a token, which is then stored for future use. An API request can be made to update brand settings at any time.

### Screenshots (if appropriate)

![image](https://github.com/canyongbs/advisingapp/assets/41773797/957a5727-092c-4e06-8c57-8e842aa6a3d9)

### Any deployment steps required?

Removal of LANDLORD_API_KEY.

2024-03-18 19:47 UTC, Orrison requested changes
Looks like some checks are currently failing.

Also, if you can make a PR to the devops repository to remove the `LANDLORD_API_KEY` `.env` key as you recommended.
Once that is merged into the Devops repo, either in this PR, or in another branch if that gets merged in, you will need to update the submodule to point to that new Hash.

I can help show you how to do that once this PR is ready to review again.

2024-03-18 19:47 UTC, Orrison commented
I'm sorry, I realize now this is a draft PR. My bad.

2024-03-19 14:42 UTC, danharrin commented
I've opened a devops PR & updated the submodule reference

2024-03-19 18:56 UTC, Orrison approved these changes

2024-03-19 19:03 UTC, merged