[ADVAPP-433]: Ensure complete test coverage for enterprise AI assistant module
canyongbs/advisingapp pull request #631
Opened 2024-04-02 19:51 UTC by danharrin

### Ticket(s) or GitHub Issue

- https://canyongbs.atlassian.net/browse/ADVAPP-433

### Technical Description

Added tests for the Livewire component that handles the AI assistant. The rest of the tests will be added in ADVAPP-446.

2024-04-02 23:02 UTC, Orrison requested changes
Look great! Just one small question.

Also it looks like there is quite a handful of issues in SonarCloud due to unused variables mostly:https://sonarcloud.io/project/issues?id=canyongbs_advisingapp&pullRequest=631&resolved=false&inNewCodePeriod=true

If it is simple to remove those that are unused as it is noting, lets do so. If not, let me know

2024-04-03 06:54 UTC, danharrin commented on app-modules/assistant/tests/Feature/Filament/Pages/AIAssistantPageTest.php
> +it('can rename a folder belonging to a different user', function () use ($setUp) {
you're right!

2024-04-03 06:54 UTC, danharrin commented on app-modules/assistant/tests/Feature/Filament/Pages/AIAssistantPageTest.php
> +it('can rename a folder belonging to a different user', function () use ($setUp) {
```suggestion
it('can not rename a folder belonging to a different user', function () use ($setUp) {
```

2024-04-03 06:57 UTC, danharrin commented
> Also it looks like there is quite a handful of issues in SonarCloud due to unused variables mostly:https://sonarcloud.io/project/issues?id=canyongbs_advisingapp&pullRequest=631&resolved=false&inNewCodePeriod=true
> 
> If it is simple to remove those that are unused as it is noting, lets do so. If not, let me know

@Orrison you can do this: https://stitcher.io/blog/array-destructuring-with-list-in-php#skip-elements, but personally I don't like the syntax and don't see a problem with having it fully written out, especially since the objects exist in memory anyway. If you want me to go ahead and refactor I can

2024-04-03 12:49 UTC, Orrison commented
> > Also it looks like there is quite a handful of issues in SonarCloud due to unused variables mostly:https://sonarcloud.io/project/issues?id=canyongbs_advisingapp&pullRequest=631&resolved=false&inNewCodePeriod=true
> > If it is simple to remove those that are unused as it is noting, lets do so. If not, let me know
> 
> @Orrison you can do this: https://stitcher.io/blog/array-destructuring-with-list-in-php#skip-elements, but personally I don't like the syntax and don't see a problem with having it fully written out, especially since the objects exist in memory anyway. If you want me to go ahead and refactor I can

Yeah I am not a fan of the regular skip syntax. That doesn't look great.

How about we apply non-numerical keys to the array and skip by only referencing what we need: https://stitcher.io/blog/array-destructuring-with-list-in-php#non-numerical-keys

Though it is a little extra text I feel like that is a nice way to only be pulling out and hydrating what is needed where it is called.

2024-04-03 13:00 UTC, dgoetzit requested changes
This looks great! Just two minor wording adjustments for tests.

2024-04-03 18:21 UTC, dgoetzit approved these changes

2024-04-03 18:23 UTC, merged