[ADVAPP-389]: Update label for Interactions > Campaigns (cleanup)
canyongbs/advisingapp pull request #651
Opened 2024-04-08 18:38 UTC by dgoetzit

### Ticket(s) or GitHub Issue

- https://canyongbs.atlassian.net/browse/ADVAPP-389

### Technical Description

> This PR cleans up and removes hanging references to the Interaction Campaign, which was removed in favor of Interaction Initiatives

### Screenshots (if appropriate)

### Any deployment steps required?

> No

_______________________________________________

#### Before contributing and submitting this PR, make sure you have Read, agree, and are compliant with the [contributing guidelines](https://github.com/canyongbs/advisingapp/blob/main/README.md#contributing).

2024-04-09 00:12 UTC, Orrison commented
@dgoetzit looks like there is a merge conflict on this.

Also, is is possible to make it into a draft since we should not merge this yet? Finally, if you can do me a favor and make sure there is a ticket for this at the top of the backlog.

2024-05-09 18:49 UTC, dgoetzit commented on app-modules/interaction/graphql/interaction.graphql
This has been restored.

2024-05-10 00:47 UTC, Orrison requested changes

2024-05-10 00:47 UTC, Orrison commented on app-modules/interaction/graphql/interaction.graphql
> +    campaign: InteractionInitiative @belongsTo
I think this probably should be called `initiative` now, right?

2024-05-10 15:47 UTC, merged