[ADVAPP-544]: Introduce ability to duplicate forms, surveys, and events
canyongbs/advisingapp pull request #720
Opened 2024-05-08 20:29 UTC by dgoetzit

### Ticket(s) or GitHub Issue

- https://canyongbs.atlassian.net/browse/ADVAPP-544

### Technical Description

> Adds replication functionality for forms, surveys, and events.

### Screenshots (if appropriate)

### Any deployment steps required?

> No

_______________________________________________

#### Before contributing and submitting this PR, make sure you have Read, agree, and are compliant with the [contributing guidelines](https://github.com/canyongbs/advisingapp/blob/main/README.md#contributing).

2024-05-09 06:33 UTC, Orrison requested changes
Let's also add a ListEventsTest similiar to the other two you wrote.

2024-05-09 06:33 UTC, Orrison commented on app-modules/form/src/Models/Form.php
> +    public function replicateRelatedData(Model $original): void
If possible, I would prefer we move this and the related methods to an Action

2024-05-09 06:33 UTC, Orrison commented on app-modules/form/tests/Filament/Resources/FormResource/Pages/ListFormsTest.php
> +    expect(Form::where('id', '<>', $form->id)->first()->steps->count())->toBe($form->steps->count());
Let's also test that no submissions were duplicated.

2024-05-09 06:33 UTC, Orrison commented on app-modules/meeting-center/src/Models/Event.php
> +    public function replicateRelatedData(Model $original): void
Same as Form, I would prefer this be moved to a separate Action class

2024-05-09 06:33 UTC, Orrison commented on app-modules/survey/src/Models/Survey.php
> +    public function replicateRelatedData(Model $original): void
Same as Form, I would prefer this be moved to a separate Action class

2024-05-09 06:33 UTC, Orrison commented on app-modules/survey/tests/Filament/Resources/SurveyResource/Pages/ListSurveysTest.php
> +    expect(Survey::where('id', '<>', $survey->id)->first()->steps->count())->toBe($survey->steps->count());
Let's also test the submissions are not duplicated

2024-05-10 01:00 UTC, Orrison requested changes

2024-05-10 01:00 UTC, Orrison commented on app-modules/survey/tests/Filament/Resources/SurveyResource/Pages/ListSurveysTest.php
> +    $submissionCount = $survey->submissions()->count();
Same as above

2024-05-10 13:31 UTC, dgoetzit commented on app-modules/form/tests/Filament/Resources/FormResource/Pages/ListFormsTest.php
> +    expect(FormSubmission::count())->toBe($submissionCount);
Yep, the factory will create between 1 and 3 submissions by default.

2024-05-10 13:32 UTC, dgoetzit commented on app-modules/survey/tests/Filament/Resources/SurveyResource/Pages/ListSurveysTest.php
> +    $submissionCount = $survey->submissions()->count();
Same as forms.

2024-05-10 13:38 UTC, dgoetzit commented on app-modules/meeting-center/tests/Filament/Resources/EventResource/ListEventsTest.php
> +    $submissionCount = $event->eventRegistrationForm->submissions()->count();
Same as forms.

2024-05-10 15:45 UTC, Orrison approved these changes

2024-05-10 15:46 UTC, Orrison requested changes
This looks good but there seems to be some test failure.

2024-05-10 20:08 UTC, Orrison commented
@mxm1070 and @dgoetzit. I see that @mxm1070 re-ran the tests in CI manually, they passed and so he re-requested my review.

I ran them again manually and I am seeing the same errors pop up again. So there is something going on / some kind of flakiness here.

2024-05-10 20:21 UTC, mxm1070 commented
@Orrison Yeah I think I've seen this one before so it's not tied to this pr. I believe it's tied to an option I added awhile ago to turn off console auditing because it was creating too many audits when I was seeding while working on the api. The config should default to true in absence of the `AUDIT_CONSOLE` env key, but I suspect CI doesn't get the the config value for some reason. I remember I had to make an `.env.testing` locally and set `AUDIT_CONSOLE=true` to fix it.

2024-05-14 13:33 UTC, Orrison approved these changes

2024-05-14 13:33 UTC, merged