[ADVAPP-559]: UI/UX enhancement on AI badge for assistant
canyongbs/advisingapp pull request #722
Opened 2024-05-09 16:24 UTC by mxm1070

### Ticket(s) or GitHub Issue

- https://canyongbs.atlassian.net/browse/ADVAPP-559

### Technical Description

Updated the assistant name styling on the personal assistant page. Updated the default assistant name.

### Screenshots (if appropriate)

<img width="1728" alt="Screenshot 2024-05-09 at 12 13 36 PM" src="https://github.com/canyongbs/advisingapp/assets/11588575/8f74e995-cdbc-48f6-8bcd-e328edb78e45">

<img width="1728" alt="Screenshot 2024-05-09 at 12 13 25 PM" src="https://github.com/canyongbs/advisingapp/assets/11588575/d4fdb5e1-a684-41e6-a2e0-4892a00ca45b">
_______________________________________________

#### Before contributing and submitting this PR, make sure you have Read, agree, and are compliant with the [contributing guidelines](https://github.com/canyongbs/advisingapp/blob/main/README.md#contributing).

2024-05-10 00:38 UTC, Orrison requested changes
This loos good but lets reduce the width of the tag to just a little more then the length of the text. That way it looks more like a tag/badge and we can update it to a button later on.

2024-05-10 00:38 UTC, Orrison commented on app-modules/assistant/src/Actions/CreateDefaultInstitutionAiAssistant.php
>          // TODO Update to reflect desired institutional defaults
This TDOD can be removed now

2024-05-10 15:34 UTC, mxm1070 commented
I've updated the screenshots.

2024-05-10 15:50 UTC, Orrison requested changes
Let's left-align the tag so that it matches what it looked like before, just in tag form.

Also I think if you rebase `main` into your branch it should fix the random test failure you have here.

2024-05-14 12:40 UTC, Orrison approved these changes

2024-05-14 12:40 UTC, merged