[ADVAPP-594]: Prevent super admin email and text messaging from counting towards customer limits
canyongbs/advisingapp pull request #777
Opened 2024-06-03 15:32 UTC by dgoetzit

### Ticket(s) or GitHub Issue

- https://canyongbs.atlassian.net/browse/ADVAPP-594

### Technical Description

> This PR adds handling to ensure we don't count emails/sms sent to Users with the `authorization.super_admin` against organizational quota usage.

### Screenshots (if appropriate)

### Any deployment steps required?

> No

_______________________________________________

#### Before contributing and submitting this PR, make sure you have Read, agree, and are compliant with the [contributing guidelines](https://github.com/canyongbs/advisingapp/blob/main/README.md#contributing).

2024-06-03 15:45 UTC, mxm1070 requested changes
Do we need to handle checking in `canSendWithinQuotaLimits` to exclude super admins from the pre-send check also?

2024-06-03 17:19 UTC, dgoetzit commented
> Do we need to handle checking in `canSendWithinQuotaLimits` to exclude super admins from the pre-send check also?

> Do we need to handle checking in `canSendWithinQuotaLimits` to exclude super admins from the pre-send check also?

I don't know if that should matter. This solution will ensure that anyone who was a super admin at the time of sending a deliverable is not counted towards the quota. If someone wasn't a super admin at the time of sending, I'm not sure it would make sense to retroactively adjust the quota.

2024-06-03 20:42 UTC, Orrison requested changes
@dgoetzit let me know that he still wants to do some work on here before review. @dgoetzit re-request my review when this is ready.

2024-06-04 16:36 UTC, Orrison requested changes
Looks good, just some small nits.

2024-06-04 16:36 UTC, Orrison commented on app-modules/notification/src/Notifications/Channels/EmailChannel.php
> +            $user = User::where('email', $recipient->getAddress())->first();
Should we add a `with('roles')` here to eager load the roles relationship for the Users?

2024-06-04 16:36 UTC, Orrison commented on app-modules/notification/src/Notifications/Channels/SmsChannel.php
> +        if ($user = User::where('phone_number', $result->message->to)->first()) {
Should we eager load `role` here?

2024-06-04 16:36 UTC, Orrison commented on tests/Unit/LicenseSettingsEmailQuotaTracking.php
> +    $notification = new Tests\Unit\TestEmailNotification();
Let's import this class

2024-06-04 17:30 UTC, Orrison approved these changes

2024-06-04 17:30 UTC, Orrison commented
@mxm1070 need you to review again since you requested changes.

2024-06-04 18:23 UTC, mxm1070 approved these changes

2024-06-04 22:39 UTC, merged