[ADVAPP-622]: Update label for Report Center to Custom Reports
canyongbs/advisingapp pull request #782
Opened 2024-06-04 10:12 UTC by payal-canyon

### Ticket(s) or GitHub Issue

- https://canyongbs.atlassian.net/browse/ADVAPP-622

### Technical Description

> Update label for Report Center to Custom Reports as well as in breadcrumb.

2024-06-04 15:45 UTC, mxm1070 approved these changes

2024-06-04 17:23 UTC, Orrison requested changes
This looks good!

Let's also change the reports list page title to match, saying "Custom Reports". And also check to see if we need to update the view, create, and edit pages to match that verbiage.

2024-06-06 13:07 UTC, payal-canyon commented
> This looks good!
> 
> Let's also change the reports list page title to match, saying "Custom Reports". And also check to see if we need to update the view, create, and edit pages to match that verbiage.

Done.

2024-06-07 15:12 UTC, Orrison approved these changes

2024-06-07 15:12 UTC, merged