[ADVAPP-621]: Introduce Report Library coming soon page under Reporting
canyongbs/advisingapp pull request #784
Opened 2024-06-04 14:53 UTC by payal-canyon

### Ticket(s) or GitHub Issue

- https://canyongbs.atlassian.net/browse/ADVAPP-621

### Technical Description

> Introduce Report Library coming soon page under Reporting.

2024-06-04 17:15 UTC, Orrison requested changes
I apologize, I forgot that we will need permissions created and enforced for this page.

Because we do not yet know the purpose of this feature we can just still with a basic `view-any` permission.

So I would create a permission called `report-library.view-any` under the PermissionGroup "Report", which should already exist.

I have yet to update the documentation to describe how to create permissions, but you can use `database/migrations/2024_05_07_143413_seed_permissions_add_manage_s3_settings.php` as an example.

Keep in mind the migration name structure is `seed_permissions_[DESCRIPTION_OF_WHAT_IS_BEING_ADDED]`

You can follow pretty much exactly what that migration does, the main difference is that you do not need to create the Group, it should already exist.

Then once the permission is created, you can add a `canAccess` method to the Page, which you can see examples of how that is done throughout the codebase.

Let me know if you have any questions!

2024-06-05 12:43 UTC, payal-canyon commented on app-modules/ai/src/Enums/AiApplication.php
Done.

2024-06-05 12:43 UTC, payal-canyon commented on app-modules/report/src/Filament/Pages/ReportLibrary.php
> +    public const APPLICATION = AiApplication::ReportLibrary;
Done.

2024-06-05 20:45 UTC, mxm1070 requested changes
Apologies, but we actually have a newer way to create permissions than the example @Orrison gave you. Please see this pr from Aiding: https://github.com/canyongbs/aidingapp/pull/82/files. 

You don't have to follow the exact structure, but please use the trait. Add a down method that handles deleting the permissions. I recommend updating the `CanModifyPermissions` trait like we did in Aiding because it makes deleting easier.

2024-06-06 10:19 UTC, payal-canyon commented
> Apologies, but we actually have a newer way to create permissions than the example @Orrison gave you. Please see this pr from Aiding: https://github.com/canyongbs/aidingapp/pull/82/files.
> 
> You don't have to follow the exact structure, but please use the trait. Add a down method that handles deleting the permissions. I recommend updating the `CanModifyPermissions` trait like we did in Aiding because it makes deleting easier.

Done.

2024-06-06 19:26 UTC, mxm1070 approved these changes

2024-06-07 15:34 UTC, Orrison approved these changes

2024-06-07 15:36 UTC, merged