[ADVAPP-642]: Update Institutional Assistant configuration for Creativeness and Response Length.
canyongbs/advisingapp pull request #804
Opened 2024-06-10 18:36 UTC by danharrin

### Ticket(s) or GitHub Issue

- https://canyongbs.atlassian.net/browse/ADVAPP-642

### Technical Description

Introduces a new slider field for setting the temp. Passes the temp and max completion length to new runs. Improves the timeout behaviour to calculate a dynamic timeout based on the current request duration.

### Any deployment steps required?

Update .env to new API version:

```
OPEN_AI_GPT_35_API_VERSION=2024-05-01-preview
OPEN_AI_GPT_4_API_VERSION=2024-05-01-preview
OPEN_AI_GPT_4O_API_VERSION=2024-05-01-preview
```

2024-06-10 21:35 UTC, Orrison requested changes
Looks like there are some test failures.

2024-06-11 13:59 UTC, mxm1070 submitted a review, later dismissed

2024-06-11 15:52 UTC, Orrison requested changes
This looks good, but requires a DevOps change. I will make the change and update the submodule in this branch soon.

2024-06-12 13:20 UTC, Orrison approved these changes

2024-06-12 13:20 UTC, merged