[ADVAPP-658]: Introduce ability to duplicate knowledge base articles
canyongbs/advisingapp pull request #837
Opened 2024-06-19 15:40 UTC by jayushi-canyon

### Ticket(s) or GitHub Issue

- https://canyongbs.atlassian.net/browse/ADVAPP-658

### Technical Description

> Add cloning feature for knowledge base articles.

_______________________________________________

#### Before contributing and submitting this PR, make sure you have Read, agree, and are compliant with the [contributing guidelines](https://github.com/canyongbs/advisingapp/blob/main/README.md#contributing).

2024-06-19 18:13 UTC, Orrison requested changes

2024-06-20 13:37 UTC, jayushi-canyon commented on app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseArticleResource/Pages/ListKnowledgeBaseArticles.php
> +                    ->label('Clone')
Done

2024-06-25 15:43 UTC, Orrison requested changes

2024-06-26 12:53 UTC, jayushi-canyon commented on app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseArticleResource/Pages/ListKnowledgeBaseArticles.php
> +                        }
This scenario has been tested and it is working fine.

2024-06-26 15:26 UTC, Orrison approved these changes

2024-06-26 15:26 UTC, merged