[ADVAPP-681]: Improve error message text for issues experienced by customers
canyongbs/advisingapp pull request #846
Opened 2024-06-24 12:14 UTC by jayushi-canyon

### Ticket(s) or GitHub Issue

- https://canyongbs.atlassian.net/browse/ADVAPP-681

### Technical Description

> Change 500 error message and image

_______________________________________________

#### Before contributing and submitting this PR, make sure you have Read, agree, and are compliant with the [contributing guidelines](https://github.com/canyongbs/advisingapp/blob/main/README.md#contributing).

2024-06-24 12:42 UTC, Orrison requested changes

2024-06-24 12:42 UTC, Orrison commented on resources/svg/flowbite-500-old.svg
Do we need to keep this file around for a particular reason? If not, I think it's okay just to delete it.

2024-06-24 13:38 UTC, jayushi-canyon commented on resources/svg/flowbite-500-old.svg
@Orrison Deleted the file

2024-06-24 20:18 UTC, Orrison requested changes

2024-06-24 20:18 UTC, Orrison commented on resources/svg/flowbite-500.svg
Let's rename this file to something more appropriate since it is no longer from Flowbite.

Let's do `canyongbs-500.svg`. Once you do so, make sure to change the reference in the blade file.

2024-06-25 17:56 UTC, jayushi-canyon commented on resources/svg/flowbite-500.svg
@Orrison Done

2024-06-25 22:38 UTC, Orrison approved these changes

2024-06-25 22:38 UTC, merged