[ADVAPP-706]: Create report for the report library for Prospects
canyongbs/advisingapp pull request #916
Opened 2024-07-18 12:51 UTC by jayushi-canyon

### Ticket(s) or GitHub Issue

- https://canyongbs.atlassian.net/browse/ADVAPP-706

### Technical Description

> Create report in report library for Prospects module

### Any deployment steps required?

> No.

### Are any Feature Flags Added?

> No.

_______________________________________________

#### Before contributing and submitting this PR, make sure you have Read, agree, and are compliant with the [contributing guidelines](https://github.com/canyongbs/advisingapp/blob/main/README.md#contributing).

2024-07-18 12:52 UTC, jayushi-canyon commented
@Orrison Created this new PR for ADVAPP-706, As there were some issue while taking latest pull from main in that branch. I will delete the previous PR.

2024-07-23 05:09 UTC, Orrison requested changes
Looks good. Just one small typo.

2024-07-23 05:09 UTC, Orrison commented on app-modules/report/src/Filament/Widgets/ProspectReportStats.php
> +                Cache::tags([$this->cacheTag])->remember('pospect-segments-count', now()->addHours(24), function (): int {
```suggestion
                Cache::tags([$this->cacheTag])->remember('prospect-segments-count', now()->addHours(24), function (): int {
```

2024-07-23 08:09 UTC, jayushi-canyon commented on app-modules/report/src/Filament/Widgets/ProspectReportStats.php
> +                Cache::tags([$this->cacheTag])->remember('pospect-segments-count', now()->addHours(24), function (): int {
@Orrison Done

2024-07-24 12:48 UTC, Orrison approved these changes

2024-07-24 12:48 UTC, merged