[ADVAPP-755]: Enhance and standardize the maximum height display for line charts in dashboards
canyongbs/advisingapp pull request #919
Opened 2024-07-22 19:35 UTC by ketan-canyon

### Ticket(s) or GitHub Issue

- https://canyongbs.atlassian.net/browse/ADVAPP-755

### Technical Description

Added abstract height for line chart.

### Any deployment steps required?

No

### Are any Feature Flags Added?

No

_______________________________________________

#### Before contributing and submitting this PR, make sure you have Read, agree, and are compliant with the [contributing guidelines](https://github.com/canyongbs/advisingapp/blob/main/README.md#contributing).

2024-07-23 05:34 UTC, Orrison requested changes

2024-07-23 05:34 UTC, Orrison commented on app-modules/report/src/Filament/Widgets/LineChartReportWidget.php
We can probably pull the following into this class as well and remove it from the child classes:

```php
protected function getType(): string
{
    return 'line';
}
```

2024-07-23 14:35 UTC, ketan-canyon commented on app-modules/report/src/Filament/Widgets/LineChartReportWidget.php
Done

2024-07-24 12:45 UTC, Orrison approved these changes

2024-07-24 12:45 UTC, merged