[ADVAPP-781]: Enhance the Prospect and Student care team experience by allowing the ability to add more than one staff member at a time
canyongbs/advisingapp pull request #940
Opened 2024-08-02 20:46 UTC by ketan-canyon

### Ticket(s) or GitHub Issue

- https://canyongbs.atlassian.net/browse/ADVAPP-781

### Technical Description

Enhance the Prospect and Student care team experience by allowing the ability to add more than one staff member at a time

### Any deployment steps required?

No

### Are any Feature Flags Added?

No
_______________________________________________

#### Before contributing and submitting this PR, make sure you have Read, agree, and are compliant with the [contributing guidelines](https://github.com/canyongbs/advisingapp/blob/main/README.md#contributing).

2024-08-05 13:23 UTC, Orrison requested changes
Looks great! Just a couple of grammatical changes are needed.

2024-08-05 13:23 UTC, Orrison commented on app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ManageStudentCareTeam.php
> +                        fn (Select $select) => $select->placeholder('Select a Users'),
```suggestion
                        fn (Select $select) => $select->placeholder('Select Users'),
```

2024-08-05 13:23 UTC, Orrison commented on app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectCareTeam.php
>                          fn (Select $select) => $select->placeholder('Select a User'),
```suggestion
                        fn (Select $select) => $select->placeholder('Select Users'),
```

2024-08-05 15:05 UTC, ketan-canyon commented on app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ManageStudentCareTeam.php
> +                        fn (Select $select) => $select->placeholder('Select a Users'),
Done

2024-08-05 15:05 UTC, ketan-canyon commented on app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectCareTeam.php
>                          fn (Select $select) => $select->placeholder('Select a User'),
Done

2024-08-06 21:41 UTC, Orrison approved these changes

2024-08-06 21:41 UTC, merged