[ADVAPP-786] Introduce Draft with AI for knowledge base articles.
canyongbs/advisingapp pull request #949
Opened 2024-08-08 16:47 UTC by ankit-canyon

### Ticket(s) or GitHub Issue

- https://canyongbs.atlassian.net/browse/ADVAPP-786

### Technical Description

> Draft knowledge base article with AI assistant when editing the article. 

### Any deployment steps required?

> No

### Are any Feature Flags Added?

> No

_______________________________________________

#### Before contributing and submitting this PR, make sure you have Read, agree, and are compliant with the [contributing guidelines](https://github.com/canyongbs/advisingapp/blob/main/README.md#contributing).

2024-08-09 20:58 UTC, Orrison requested changes
Looks good. Just a couple of notes.

I would like @danharrin to review as well.

2024-08-09 20:58 UTC, Orrison commented on app-modules/knowledge-base/src/Filament/Actions/DraftWithAiAction.php
> +                                    Please provide the title as a plain string, without any prefixes, labels like "Title:", or formatting such as bold, italics, or quotes. The title should appear as
You may want to be explicit that the title and content should have a newline separation between them like we do for the Engagement prompt

2024-08-09 20:58 UTC, Orrison commented on app-modules/knowledge-base/src/Filament/Actions/DraftWithAiAction.php
> +class DraftWithAiAction extends Action
Let's rename this `DraftKnowledgeBaseArticleWithAiAction` and related blade file, etc. so we can differentiate it from others.

2024-08-12 17:37 UTC, danharrin requested changes

2024-08-12 17:37 UTC, danharrin commented on app-modules/knowledge-base/src/Filament/Actions/DraftKnowledgeBaseArticleWithAiAction.php
> +    }
Please remove the merge tag methods and the merge tags property from here as they aren't used in this context

2024-08-12 19:01 UTC, Orrison requested changes
This looks good but let's remove the unused merge tags details as @danharrin mentioned

2024-08-13 16:36 UTC, Orrison requested changes
This looks good to me. @danharrin if you can re-review and mark your comments resolved if they are.

2024-08-13 16:37 UTC, Orrison approved these changes

2024-08-13 18:15 UTC, danharrin approved these changes

2024-08-13 18:15 UTC, merged