[ADVAPP-811] Introduce the ability to convert a Prospect into a Student
canyongbs/advisingapp pull request #980
Opened 2024-08-22 09:31 UTC by ankit-canyon

### Ticket(s) or GitHub Issue

- https://canyongbs.atlassian.net/browse/ADVAPP-811

### Technical Description

> Introduce a Convert button on a Prospect Record, which covert a prospect into student record.

### Any deployment steps required?

> No

### Are any Feature Flags Added?

> Yes
> Added "convert_prospect_to_student" feature flag.

_______________________________________________

#### Before contributing and submitting this PR, make sure you have Read, agree, and are compliant with the [contributing guidelines](https://github.com/canyongbs/advisingapp/blob/main/README.md#contributing).

2024-08-22 20:17 UTC, Orrison requested changes
This looks good but I had a few notes.

Also overarching, I think it would be best if the placement of the convert notice was changed. I believe it would be best going all across the top of the content. Perhaps the Render Hook `PanelsRenderHook::PAGE_START` may work better than this widget.
Also this notice needs to be present on all pages within the Student Holistic view. Not just View and Edit, but "Emails & Texts" etc.

2024-08-22 20:17 UTC, Orrison commented on app-modules/prospect/src/Filament/Resources/ProspectResource/Widgets/ConvertedStudentBadge.php
> +    protected static string $view = 'filament.widgets.student-converted-badge';
This view should be put within the `prospects` module and then this reference namespaced

2024-08-22 20:17 UTC, Orrison commented on app-modules/prospect/tests/Prospect/EditProspectTest.php
> +        ->mountAction(ConvertToStudent::class)
Is this `mountAction` call needed?

2024-08-22 20:17 UTC, Orrison commented on app-modules/prospect/tests/Prospect/EditProspectTest.php
> +    expect($prospect->student()->exists())->toBeTrue();
You should assert that the relationship is to the `Student` that you expect it to be

2024-08-22 20:17 UTC, Orrison commented on app-modules/prospect/tests/Prospect/EditProspectTest.php
> +        ->mountAction(DisassociateStudent::class)
Is this `mountAction` call needed?

2024-08-22 20:17 UTC, Orrison commented on app-modules/prospect/tests/Prospect/ViewProspectTest.php
> +    expect($prospect->student()->exists())->toBeTrue();
You should assert that the relationship is to the Student that you would expect.

2024-08-22 20:17 UTC, Orrison commented on app-modules/prospect/tests/Prospect/ViewProspectTest.php
> +        ->mountAction(ConvertToStudent::class)
Is this `mountAction` call needed?

2024-08-22 20:17 UTC, Orrison commented on app-modules/prospect/tests/Prospect/ViewProspectTest.php
> +        ->mountAction(DisassociateStudent::class)
Is this `mountAction` call needed?

2024-08-24 03:17 UTC, Orrison commented
> > This looks good but I had a few notes.
> > Also overarching, I think it would be best if the placement of the convert notice was changed. I believe it would be best going all across the top of the content. Perhaps the Render Hook `PanelsRenderHook::PAGE_START` may work better than this widget. Also this notice needs to be present on all pages within the Student Holistic view. Not just View and Edit, but "Emails & Texts" etc.
> 
> Hi @Orrison ,
> 
> You mean the Prospect Holistic view here?
> 
> Thank you.

Yes, sorry. I meant the Prospect Holistic View

2024-08-24 03:50 UTC, ankit-canyon commented
> > > This looks good but I had a few notes.
> > > Also overarching, I think it would be best if the placement of the convert notice was changed. I believe it would be best going all across the top of the content. Perhaps the Render Hook `PanelsRenderHook::PAGE_START` may work better than this widget. Also this notice needs to be present on all pages within the Student Holistic view. Not just View and Edit, but "Emails & Texts" etc.
> > 
> > 
> > Hi @Orrison ,
> > You mean the Prospect Holistic view here?
> > Thank you.
> 
> Yes, sorry. I meant the Prospect Holistic View

Yep ! I that's I already done with the recent changes.

2024-08-26 13:04 UTC, Orrison requested changes
Looking good, just a comment.

Also lets make tests ensuring that the blade render hook shows or does not show the banner when the Student is in the correct configuration for each page.

It also seems that the banner is not on the Programs page

2024-08-26 13:04 UTC, Orrison commented on app-modules/prospect/resources/views/student-converted-badge.blade.php
> +@if (Feature::active('convert_prospect_to_student') && $this->getRecord()->student)
Let's make sure to import the `Feature` class, it's interesting that it seems to be finding it on it's own now. But best to be explicit.

2024-08-28 09:01 UTC, Orrison requested changes

2024-08-28 20:05 UTC, Orrison approved these changes

2024-08-28 20:13 UTC, merged